# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: test1
services:
  app:
    image: test1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_COUCHBASE_CONNECTION_STRING=couchbase
      - JHIPSTER_DATABASE_COUCHBASE_BUCKET_NAME=test1
      - JHIPSTER_SLEEP=20
      - SPRING_PULSAR_CLIENT_SERVICE_URL=pulsar://pulsar:6650
      - SPRING_PULSAR_ADMINISTRATION_SERVICE_URL=http://pulsar:8080
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      couchbase:
        condition: service_healthy
  couchbase:
    extends:
      file: ./couchbase.yml
      service: couchbase
  pulsar:
    extends:
      file: ./pulsar.yml
      service: pulsar
